### ISSUE TITLE
Master key should not be input with env or args

### ISSUE THREAD

**Issue by zhongguozhang** [CovenantSQL/CovenantSQL#106]
查看自己的钱包余额时，如果之前有输入master key，则提示失败。

错误提示如下：

./cql -config conf/config.yaml -get-balance

ERRO[0000] decrypt private key error caller="privatekeystore.go:50 crypto/kms.LoadPrivateKey"

INFO[0000] load private key failed: invalid PKCS#7 padding caller="privatekeystore.go:90 crypto/kms.InitLocalKeyPair"

ERRO[0000] unexpected error while loading private key: invalid PKCS#7 padding caller="privatekeystore.go:109 crypto/kms.InitLocalKeyPair"

ERRO[0000] init covenantsql client failed: invalid PKCS#7 padding caller="main.go:196 main.main"

**Comment by auxten** [comment]
You can try `-password` to pass a master key.
This is vulnerable and will be changed to use an interactive way to let user input master key in the console.

**Comment by zhongguozhang** [comment]
测过了， ./cql -config conf/config.yaml -get-balance -password xxxxxx 这样可以

**Comment by auxten** [comment]
Fixed at #284
