### ISSUE TITLE
testnet.covenantsql.io上facebook发完有检测不到的情况

### ISSUE THREAD

**Issue by zhongguozhang** [CovenantSQL/CovenantSQL#107]
facebook发完后，提示为 “你的帖子没有包含我们需要的 URL，请复制步骤1中的文字重新发送”。

我试着连发了几次，都不行。

**Comment by foreseaz** [comment]
@zhongguozhang could you paste your facebook post URL here? We will look into it later, thanks.

**Comment by zhongguozhang** [comment]
> @zhongguozhang could you paste your facebook post URL here? We will look into it later, thanks.

https://www.facebook.com/permalink.php?story_fbid=572303423183920&id=100012128029311

**Comment by auxten** [comment]
Sorry for that, we have a new quickstart doc but only in Chinese for now, please try it: https://developers.covenantsql.io/docs/quickstart

**Comment by auxten** [comment]
You can refer to #283
