### ISSUE TITLE
用 cql 来查看你的钱包余额时出错

### ISSUE THREAD

**Issue by fanjianhang** [CovenantSQL/CovenantSQL#111]
[root@localhost bin]# cql -config conf/config.yaml -get-balance
ERRO[0001] connect to 120.79.254.36:11105 failed: dial tcp 120.79.254.36:11105: connect: connection refused  caller="client.go:60 rpc.dial"
ERRO[0001] connect to 120.79.254.36:11105: dial tcp 120.79.254.36:11105: connect: connection refused  caller="client.go:156 rpc.dialToNodeEx"
ERRO[0001] dialToNode failed: dial tcp 120.79.254.36:11105: connect: connection refused  caller="client.go:99 rpc.DialToNode"
ERRO[0001] dialing to node: 0000011839f464418166658ef6dec09ea68da1619a7a9e0f247f16e0d6c6504d failed: dial tcp 120.79.254.36:11105: connect: connection refused  caller="rpcutil.go:140 rpc.(*Caller).CallNodeWithContext"
ERRO[0001] call DHT.Ping failed: dial tcp 120.79.254.36:11105: connect: connection refused  caller="rpcutil.go:253 rpc.PingBP"
ERRO[0001] init covenantsql client failed: dial tcp 120.79.254.36:11105: connect: connection refused  caller="main.go:196 main.main"

**Comment by zeqing-guo** [comment]
We are updating our testnet. It will work tomorrow.

**Comment by zeqing-guo** [comment]
`cql` can work properly now:)
