### ISSUE TITLE
Error with fio test on cql-fuse

### ISSUE THREAD

**Issue by Daniel-Robbins** [CovenantSQL/CovenantSQL#123]
With FUSE support is awesome, but some bugs here

1. mount CovenantFS with
`./cql-fuse -config conf/config.yaml -dsn covenantsql://0c07e3f6d8a57511d70955a3cfd7311895ab05ad5d7303279bf78dc2df40c17c -mount ./mnt`
2. then cd to the ./mnt dir, run fio
`fio --loops=2 --size=100m --filename=./fiotest.tmp --stonewall --name=Seqread --bs=1m --rw=read   --name=Seqwrite --bs=1m --rw=write   --name=4krandread --bs=4k --rw=randread   --name=4krandwrite --bs=4k --rw=randwrite`

fio test Seqread failed and produced these logs:

```
ERRO[0019] call RPC failed                               caller="rpcutil.go:103 rpc.(*PersistentCaller).Call" error="too many SQL variables" rpc=DBS.Query stack="[#0 rpc.(*PersistentCaller).Call@rpcutil.go:103      #1 client.(*conn).sendQuery@conn.go:352      #2 client.(*conn).Commit@conn.go:251      #3 database/sql.(*Tx).Commit.func1@sql.go:2007      #4 database/sql.withLock@sql.go:3074      #5 database/sql.(*Tx).Commit@sql.go:2006      #6 client.ExecuteInTx@tx.go:43      #7 client.ExecuteTx@tx.go:35      #8 main.(*Node).Setattr@node.go:184      #9 vendor/bazil.org/fuse/fs.(*Server).handleRequest@serve.go:945     ]"
2018/11/19 16:25:02 too many SQL variables
```

**Comment by auxten** [comment]
Fixed #224
