### ISSUE TITLE
Could not run in docker based alpine image

### ISSUE THREAD

**Issue by laodouya** [CovenantSQL/CovenantSQL#134]
Maybe missing libc, could you build static instead?

**Comment by xq262144** [comment]
I'm sure we added the static flag during build process. https://github.com/CovenantSQL/CovenantSQL/blob/develop/Dockerfile#L6

**Comment by laodouya** [comment]
Oh, I see. Leave it to me.

**Comment by laodouya** [comment]
#142 Replace running docker image to alpine with glibc version.
