### ISSUE TITLE
Static build get some warnings about glibc

### ISSUE THREAD

**Issue by laodouya** [CovenantSQL/CovenantSQL#143]
![image](https://user-images.githubusercontent.com/4847103/50286664-0e6d5900-049b-11e9-82b9-036b3bb3fba6.png)
`dlopen getaddrinfo getgrouplist getgrgid_r getgrnam_r getpwnam_r getpwuid_r` 
Temporally change running docker image to glibc version alpine in this commit https://github.com/CovenantSQL/CovenantSQL/pull/142/commits/ace6fa58872b71b6cbccdfc1be9917c1a0622611

**Comment by auxten** [comment]
`dlopen` in sqlite should be disabled

**Comment by xq262144** [comment]
Fixed in e40caf2fa8c2d1e57a3623fdee2a748bebb36aab
