### ISSUE TITLE
Private Key Format should be human readable

### ISSUE THREAD

**Issue by auxten** [CovenantSQL/CovenantSQL#144]
# Background

CovenantSQL Private Key is [encrypted with user inputted master key with a key hash suffix but stored in binary](https://github.com/CovenantSQL/CovenantSQL/blob/develop/crypto/kms/privatekeystore.go#L74). It's not suitable for copy & paste or backup.

# Goal
Private Key serialization and format can be identical with Bitcoin：
  1. https://en.bitcoin.it/wiki/Private_key
  2. https://en.bitcoin.it/wiki/Mini_private_key_format

**Comment by draveness** [comment]
this maybe a broken change, is it acceptable? Or do I need to implement a compatible version for the original private key file loading function `LoadPrivateKey`?

**Comment by auxten** [comment]
compatible is better
