### ISSUE TITLE
Blocks are not written to chain

### ISSUE THREAD

**Issue by xunconnectedx** [CovenantSQL/CovenantSQL#219]
In bp logs there are messages that blocks are created, from miner to messages displayed cached_block_count (increases with each block). However, no blocks are added to the chain itself
Only the first empty block is displayed in the Explorer
Used the latest version from github for testing. Starting with 'make start'

![image](https://user-images.githubusercontent.com/22150893/51239153-cf033100-19a2-11e9-98c4-4e50f73d039b.png)

![image](https://user-images.githubusercontent.com/22150893/51239003-6ddb5d80-19a2-11e9-9743-fcb7748da841.png)

**Comment by zeqing-guo** [comment]
We enabled permission checking on database, so observer cannot fetch block from database without permission. Please use admin key to grant read permission to observer address before starting observer in docker.

**Comment by xunconnectedx** [comment]
> We enabled permission checking on database, so observer cannot fetch block from database without permission. Please use admin key to grant read permission to observer address before starting observer in docker.

Write how to do it, please. I think not only me could be a question :)

**Comment by zeqing-guo** [comment]
Hi, we wrote a doc for granting observer read permission: https://developers.covenantsql.io/docs/deployment#sqlchain-explorer

If you have any further questions, please don't hesitate to contact me.
