### ISSUE TITLE
get stable coin balance failed

### ISSUE THREAD

**Issue by seiferxiii** [CovenantSQL/CovenantSQL#245]
Hey, im simply following the instructions found on https://testnet.covenantsql.io/quickstart, but i am experiencing "get stable coin balance failed"

INFO[0006] read full failed error="read tcp 192.168.100.207:51094->39.98.191.190:7777: 
read: connection reset by peer"
ERRO[0006] get stable coin balance failed caller="main.go:215 main.main" error="broken pipe" stack="[#0 main.main@main.go:215      #1 runtime.main@proc.go:198      #2 runtime.goexit@asm_amd64.s:2361     ]"

Is this simply a firewall issue or what?

**Comment by auxten** [comment]
Please refer to: #283

**Comment by auxten** [comment]
It's our update broke the API. 
So, you can just use the [newest release](https://github.com/CovenantSQL/CovenantSQL/releases) and the client [conf](https://github.com/CovenantSQL/CovenantSQL/blob/develop/conf/testnet/config.yaml) and [private key](https://github.com/CovenantSQL/CovenantSQL/blob/develop/conf/testnet/private.key) for test net
