### ISSUE TITLE
I have developed an Excel add-in for this project

### ISSUE THREAD

**Issue by melancholiaforever** [CovenantSQL/CovenantSQL#281]
First of all, Thank you guys for offering me such a good SQL Database to use.

I stored some macro economy & finance data in this database, and developed a excel add-in to browser massive data & export it easier.  

Here is my work's source code: https://github.com/melancholiaforever/CQL_Excel

if u guys want other  add-in such as MATLAB or R, I may give a hand.

**Comment by auxten** [comment]
Thanks very much!
Your add-in is great. 
And, yes, we need all kinds of clients and drivers to make it easy to access data in CovenantSQL.

Thanks again for your fabulous work!
