### ISSUE TITLE
生成的钱包地址无效

### ISSUE THREAD

**Issue by Big-Aaron** [CovenantSQL/CovenantSQL#282]
ERRO[0004] get Particle balance failed                   error="no such token balance"

另外，申请水龙头是报错钱包地址无效

**Comment by auxten** [comment]
你执行的命令是什么？

**Comment by Big-Aaron** [comment]
> 你执行的命令是什么？

./cql-utils -tool addrgen -private ~/.cql/private.key

**Comment by Big-Aaron** [comment]
文档上的命令

**Comment by auxten** [comment]
水龙头下线了，你把钱包地址贴在这里，我给你转 token 吧

**Comment by Big-Aaron** [comment]
> 水龙头下线了，你把钱包地址贴在这里，我给你转 token 吧

wallet address: 230760b05bb1fa94aa0b8dd8e926ac72167eed969db6f5843dc04429afe56a44

**Comment by Big-Aaron** [comment]
麻烦了

**Comment by auxten** [comment]
是我们做的不好，文档没有及时更新。好了，可以用 `./cql -get-balance` 看到你的余额了
