### ISSUE TITLE
[Document] some Quickstart pages are outdated

### ISSUE THREAD

**Issue by jychen7** [CovenantSQL/CovenantSQL#309]
**Describe the bug**
https://covenantsql.io/blog/quickstart-zh?lang=zh is outdated
https://testnet.covenantsql.io/quickstart is outdated

no `cql-utils` anymore after https://github.com/CovenantSQL/CovenantSQL/releases/tag/v0.5.0

**Expected behavior**
english version of https://developers.covenantsql.io/docs/quickstart, which is updated

**Comment by foreseaz** [comment]
@jychen7 thanks for your issue, we are intensively updating the docs recently, so the Chinese and English versions are not matched. When the new version of docs is live, we will get back you. Thanks.

**Comment by auxten** [comment]
Please check our new docs site: http://developers.covenantsql.io
