### ISSUE TITLE
cql 增加一个 update 更新自己的命令（参考nvm）

### ISSUE THREAD

**Issue by eyun-tv** [CovenantSQL/CovenantSQL#343]
cql 增加一个 update 更新自己的命令（参考nvm）https://github.com/nvm-sh/nvm

**Comment by laodouya** [comment]
如果您使用MacOS，可以尝试`brew upgrade cql`。其他linux发行版的集成我们还在开发中。

**Comment by auxten** [comment]
> 如果您使用MacOS，可以尝试`brew upgrade cql`。其他linux发行版的集成我们还在开发中。

一般命令行工具都不做自更新，homebrew 也不建议工具做自更新
