### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shangmacun** [CovenantSQL/CovenantSQL#50]
Sending build context to Docker daemon  55.5 MB
Step 1/16 : FROM golang:1.10.3-stretch as builder
Error parsing reference: "golang:1.10.3-stretch as builder" is not a valid repository/tag: invalid reference format
make: *** [build] Error 1

**Comment by ggicci** [comment]
Please update Dockerfile `golang:1.10.3-stretch` to `golang:1.10-stretch`. @leventeliu
