### ISSUE TITLE
Where can I find covenantsql.io/covenantsql_adapter

### ISSUE THREAD

**Issue by ming535** [CovenantSQL/CovenantSQL#53]
Hi, where can I find this docker image `covenantsql.io/covenantsql_adapter`?

It's not on docker hub, and there is no instruction to build it from source code.

**Comment by xq262144** [comment]
Thank you for your kind attention on the CovenantSQL project.
Unfortunately, the covenantsql_adapter feature is currently being close-sourced and the docker script  contains this covenantsql_adapter image definition currently is purposed for internal uses.
However, we are working on the project TestNET and quickstart documentations including heavily detailed usage docs, API docs, and example program for major programming languages.
The TestNET and related documentation will be released soon in a few weeks.
Thank you again and please stay tuned for our upcoming TestNET and release.

**Comment by ghost** [comment]
Adding myself here to be notified when the TestNet is made public

**Comment by auxten** [comment]
hey guys, we have just released our v0.0.1 [TestNet](https://testnet.covenantsql.io/) and [Quick Start](https://testnet.covenantsql.io/quickstart). Please check it out.

**Comment by auxten** [comment]
@xq262144 need some doc for adapter and Java-connector

**Comment by auxten** [comment]
[CovenantSQL 一键开箱使用](https://github.com/CovenantSQL/CovenantSQL/wiki/CovenantSQL-%E4%B8%80%E9%94%AE%E5%BC%80%E7%AE%B1%E4%BD%BF%E7%94%A8)
