### ISSUE TITLE
Stuck in 2pc inconsistent state error

### ISSUE THREAD

**Issue by laodouya** [CovenantSQL/CovenantSQL#56]
I've used the http api to save some data, and i've created a database success.
But when I tried to insert a bulk sql request for more than 3000 line, like 'insert or replace into xxx values(xxx)', I got `{'data': None, 'status': 'process log: invalid request supplied', 'success': False}`  error.
I tried again, got `{'data': None, 'status': 'process log: twopc: inconsistent state, currently in tx: conn = 1491013221004001315, seq = 1, time = 1536228051350372242', 'success': False}` error instead, and this database could never accecpt any command, but only this error returned.

Please help me check what's wrong and how to get it right. My database id is `053d0bb19637ffc7b4a94e3c79cc71b67a768813b09e4b67f1d6159902754a8b`

**Comment by leventeliu** [comment]
Seems like an adapter issue, @xq262144 is working on it.
