### ISSUE TITLE
Any plan to NodeJS support?

### ISSUE THREAD

**Issue by Daniel-Robbins** [CovenantSQL/CovenantSQL#80]

**Comment by foreseaz** [comment]
Hi Daniel, supporting NodeJS is exactly the next step in our plan, our drivers will cover most of popular language in market and will be released soon. Stay tuned!

**Comment by foreseaz** [comment]
@Daniel-Robbins good day! You can check out our beta version of NodeJS driver [here](https://github.com/CovenantSQL/node-covenantsql), it's still under development but you can give it a try. You can open a issue [here](https://github.com/CovenantSQL/node-covenantsql/issues/new) when encounter any problem.
