### ISSUE TITLE
Quickstart cli document 404

### ISSUE THREAD

**Issue by coffin5257** [CovenantSQL/CovenantSQL#97]
`CLI README` document url not found in the [quickstart](https://testnet.covenantsql.io/quickstart).
In addition, `cql` command needs master key (with `-password master-key`) if the key is not empty by default.This should be mentioned in the document.

**Comment by nmreadelf** [comment]
hahahaha

**Comment by auxten** [comment]
Fixed at [cc39598](https://github.com/CovenantSQL/CovenantSQL/commit/cc395981277a44ea2c1cafea224370857a84afdc)
